### ISSUE TITLE
Add RPC client to MAS

### ISSUE THREAD

**Issue by hashsploit** [hashsploit/clank#23]
Add an RPC client to MAS for communicating with MLS for account mgmt.

Suggested endpoints:
- PlayerLogin(username, password) -> (success, account_id, other info)
- PlayerInfo(username) -> (player info)
- BanPlayer(username, duration, reason) -> (success)
- BanPlayerId(account_id, duration, reason) -> (success)
- KickPlayer(username, reason) -> (success)
- KickPlayerId(account_id, reason) -> (success)

**Comment by jtjanecek** [comment]
Added:
PlayerLogin(username, password) -> (success, account_id, other info)

Will re-open issue on others when implementation needed
