### ISSUE TITLE
Broadcasting message in MLS causes disconnecting

### ISSUE THREAD

**Issue by Speedy11CZ** [hashsploit/clank#67]
After broadcasting message to all players on MLS, all will be disconnected.

> MLS> broadcast 10 message
09:05:01.870 [INFO] Sent system message 'message' to 1 client(s).
09:05:06.054 [INFO] PlayerStatus updated: Player[Username: 'speedy11cz', Session                                                                                                                                                             Key: 9cfd885c1bffe14a, Status: MEDIUS_PLAYER_IN_CHAT_WORLD, accountId: 1, ChatWo                                                                                                                                                             rld: 0]
09:05:06.058 [INFO] Player 'speedy11cz' has authenticated their session key: 9cf                                                                                                                                                             d885c1bffe14a
09:05:06.059 [INFO] PlayerStatus updated: Player[Username: 'speedy11cz', Session                                                                                                                                                             Key: 9cfd885c1bffe14a, Status: MEDIUS_PLAYER_IN_CHAT_WORLD, accountId: 1, ChatWo                                                                                                                                                             rld: 0]
09:05:06.060 [INFO] Player 'speedy11cz' has authenticated their session key: 9cf                                                                                                                                                             d885c1bffe14a
09:05:21.164 [INFO] Client disconnected: 10.0.0.2:9770

**Comment by hashsploit** [comment]
The System Message severity disconnect depends on game, if you do `broadcast 0 My Message` in UYA you will see it does not disconnect you. -- The client is the one that disconnects first.
