### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "packets" is null

### ISSUE THREAD

**Issue by Veritas83** [hashsploit/clank#87]
I'm getting NullPointerException in both Win10 and Debian

<pre>
Initializing ...
03:26:20.991 [INFO] Clank v0.1.7 (starting MEDIUS_UNIVERSE_INFORMATION_SERVER)
03:26:21.207 [FINEST] Universes: [name=GT4, description=GT4, hostname=gt4-pubeta.muis.pdonline.scea.com, port=10075, applicationId=10782, universeId=1]
03:26:21.218 [INFO] Starting TCP server with 1 parent thread(s), and 4 child thread(s) ...
03:26:21.382 [INFO] TCP server started on 192.168.0.228:10071
03:26:38.420 [FINE] Client connected: 192.168.0.222:18882
03:26:38.442 [FINE] /192.168.0.222:18882: channel active
03:26:38.479 [FINEST] Deframe pipeline input: 240a0002006e006d0001000100
03:26:38.481 [FINEST] Deframe pipeline out: 240a0002006e006d0001000100
03:26:38.485 [FINEST] Raw data: 240a0002006e006d0001000100
03:26:38.488 [INFO] java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "packets" is null

03:26:38.490 [INFO]     at net.hashsploit.clank.server.pipeline.TestHandlerMUIS.channelRead(TestHandlerMUIS.java:70)

03:26:38.497 [INFO]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)</pre>

**Comment by Jump-Suit** [comment]
This issue can now be closed due to the recent PR merge: https://github.com/hashsploit/clank/commit/c7c4b2e3066ec4b5668b7ace03407007ac984b60 
As the new handler now deprecates the old `TestHandlerMUIS.java`.

**Comment by hashsploit** [comment]
Thanks!
